// <auto-generated />
using System;
using BarotraumaJWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarotraumaJWT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250518151649_relationFix")]
    partial class relationFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarotraumaJWT.Models.Characters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubmarineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubmarineId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("BarotraumaJWT.Models.Submarine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Model")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Submarines");
                });

            modelBuilder.Entity("BarotraumaJWT.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarotraumaJWT.Models.Characters", b =>
                {
                    b.HasOne("BarotraumaJWT.Models.User", null)
                        .WithMany("CreatedCharacters")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarotraumaJWT.Models.Submarine", null)
                        .WithMany("Tripulates")
                        .HasForeignKey("SubmarineId");
                });

            modelBuilder.Entity("BarotraumaJWT.Models.Submarine", b =>
                {
                    b.Navigation("Tripulates");
                });

            modelBuilder.Entity("BarotraumaJWT.Models.User", b =>
                {
                    b.Navigation("CreatedCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
